### PR TITLE
Fixing mistakes in README

### LINKED ISSUE #59: Some comments on the readme file
### Description
1. Not a bug really, but some clarifications to the readme file could be good.
Under Getting Started, the iOS header says "Optional". and then the text says "this plugin must be initialized in..". Is it optional or does it have to be initialized?

2. The code sample seems to have a typo.
public UIViewController GetTopViewController()
{
    var window = UIApplication.SharedApplication.KeyWindow.RootViewController;

    if (vc is UINavigationController navController)
        vc = navController.ViewControllers.Last();

    return vc;
}

shouldn't "window" be "vc"?

### PR DESCRIPTION
**Pull request by dimonovdd**
### Related to issue
- Closes #59

### CODE REVIEW

**Comment by dimonovdd** [comment]
@Brosten Thanks. Do you have any other comments?

**Comment by Brosten** [comment]
Shouldn't the method be more like?
```
public UIViewController GetTopViewController()
{
    var window = UIApplication.SharedApplication.KeyWindow.RootViewController;

    if (window is UINavigationController navController)
        return navController.ViewControllers.Last();

    return null;
}
```

And the iOS part is still confusing.
Why is it optional. If I don't have to initialize it, why do it? An explanation of pros and cons with iOS init would be nice!

**Comment by dimonovdd** [comment]
I do not know how to explain that. It's quite difficult. I would have to talk about [View Controllers in iOS](https://developer.apple.com/documentation/uikit/view_controllers). 

I just thought that those who need it will understand it anyway. And others do not need to do anything

**Comment by Brosten** [comment]
But for the ones who don't really understand it (like me). If I understand it correctly, everything will work perfect without the init code.

So, why should anyone else bather doing the init?
Perhap's provide a link to some place explaining the optional init thing...?

**Comment by dimonovdd** [comment]
> Perhap's provide a link to some place explaining the optional init thing...?
The link is in my previous message. 

Perhaps this will be useful in native Xamarin.iOS  projects that do not use Xamarin.Forms or if you make custom [View Controllers](https://developer.apple.com/documentation/uikit/view_controllers) for Xamarin.Forms.

**Pull request merged**
