### PR TITLE
Maui support

### PR DESCRIPTION
**Pull request by dimonovdd**
### Related to issue
- Closes: #103
- Closes: #98 

### PR Checklist ###

- [ ] All projects build
- [ ] Has samples
- [ ] Rebased onto current `main`

### CODE REVIEW

**Comment by dimonovdd** [comment]
[2.1.2-alpha001](https://www.nuget.org/packages/Xamarin.MediaGallery/2.1.2-alpha001#dependencies-body-tab) version has been published. But there are strange problems with restoring packages. You can try to run `Xamarim.MediaGallery.Sample.sln` from this branch.

telegram-cloud-photo-size-2-5472208349002057136-y

**Comment by KSemenenko** [comment]
also seems we have to add .net 7 support too

**Comment by dimonovdd** [comment]
> also seems we have to add .net 7 support too, I will check this error

Let's do it later

**Comment by dimonovdd** [comment]
It seems worth separating the nuget

**Comment by dimonovdd** [comment]
@KSemenenko You can try [2.1.2-alpha002](https://www.nuget.org/packages/Xamarin.MediaGallery/2.1.2-alpha002) version. It seems to me that everything is working well

**Comment by KSemenenko** [comment]
looks like it's ok

**Pull request merged**
