### PR TITLE
File scoped namespace

### PR DESCRIPTION
**Pull request by dimonovdd**
### PR Checklist ###

- [x] All projects build
- [x] Has samples
- [x] Rebased onto current `main`

### CODE REVIEW

**Comment by beeradmoore** [comment]
This PR won't build for me, it has the opposite problem of the other PR.

MediaGallery is using MAUI `8.0.92` but `Sample.MAUI` is using `$(MauiVersion)`. 

When I try build I get

> 1>Sample.Maui.csproj: Error NU1605 : Warning As Error: Detected package downgrade: Microsoft.Maui.Controls from 8.0.92 to 8.0.82. Reference the package directly from the project to select a different version. 
>  Sample.Maui -> Xamarin.MediaGallery -> Microsoft.Maui.Controls (>= 8.0.92) 
>  Sample.Maui -> Microsoft.Maui.Controls (>= 8.0.82)

This is because my Mac has an outdated MAUI installed via workloads, as I use MAUI via nuget packages only so I don't bother updating it.

```
$ sudo dotnet workload list
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
macos                      15.0.8303/8.0.100      SDK 8.0.400        
ios                        18.0.8303/8.0.100      SDK 8.0.400        
maccatalyst                18.0.8303/8.0.100      SDK 8.0.400        
maui                       8.0.82/8.0.100         SDK 8.0.400        
android                    34.0.143/8.0.100       SDK 8.0.400       
```

This is where it has version incompatibilities. 



We can leave it for now and I can change my local copy to build, and then when this and #130 are merged we can do another PR to handle MAUI versions (which also handles the comment I love on the other PR).

**Comment by dimonovdd** [comment]
I think this pull request has nothing to do with the MAUI version. Do you have any comments on the changes from this Pull Request? 

Sorry, I have a habit related to my work. We try to make each change separately.

**Comment by beeradmoore** [comment]
> Sorry, I have a habit related to my work. We try to make each change separately.

Thats all good, so long as we can come back to it later. I was more pointing out that the issue that I brought up the other day that using `$(MauiVersion)` can break things, and then it did 😅. Not sure why it didn't break in the other PR though. Hopefully does not mean any conflicts. More than happy to deal with it later to have a PR just for it, that make sense to keep things organised. 

I'll have a closer look at this over the next 12h. The git diff looks a bit broken so I want to pay extra attention. But from what I understand its just changing namespaces to be file scoped and then reducing the indent in by one?

**Review by beeradmoore — APPROVED** [review]
Was able to view what is happening a lot easier after hiding whitespace.

**Pull request merged**
