### PR TITLE
Upd sample

### PR DESCRIPTION
**Pull request by dimonovdd**
### PR Checklist ###

- [x] All projects build
- [x] Has samples
- [x] Rebased onto current `main`

### CODE REVIEW

**Comment by beeradmoore** [comment]
In this PR can we change the MAUI version in MediaGallery down to `8.0.3`?

Reason being that it is currently `8.0.92`, but if my app is using `8.0.82` I won't be able to use the nuget generated as its minimum is higher than my current. At least if it's `8.0.3` it should lock to .NET 8 MAUI apps, and it will internally use whatever their main app is currently using. Keeping it at `8.0.92` in the sample project is the right call.

**Comment by dimonovdd** [comment]
I haven't researched how all these versions work in MAUI yet. In this PR, I tried only to correct the code style and gross errors in Sample project.

**Comment by beeradmoore** [comment]
No worries, I'll get though this in the next 12h.

**Review by beeradmoore — APPROVED** [review]
Looks good. There was a few Android changes so ran it on my Android device as well as reviewing code, worked great.

**Pull request merged**
